spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventario_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null
server:
  port: 8080